# Generated by Django 5.1 on 2024-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Karnali', 'Karnali'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Janakpur', 'Janakpur'), ('Sudurpashchim', 'Sudurpashchim'), ('Bagmati', 'Bagmati'), ('Biratnagar', 'Biratnagar'), ('Hetauda', 'Hetauda'), ('Kathmandu', 'Kathmandu'), ('Province1', 'Province1')], max_length=100),
        ),
    ]
