# Generated by Django 5.1 on 2024-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_khalti_paymerit_status_payment_khalti_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='payment',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On . The .Way', 'On. The.Way'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
