# Generated by Django 5.1 on 2024-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_payment_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On . The .Way', 'On. The.Way'), ('Pending', 'Pending'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
