# Generated by Django 5.1 on 2024-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On . The .Way', 'On. The.Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
