# Generated by Django 5.1 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderplaced_payment_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='khalti_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='khalti_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='khalti_payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On . The .Way', 'On. The.Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
