# Generated by Django 5.1 on 2024-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_payment_khalti_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('esewa', 'esewa')], default='Cash On Delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On . The .Way', 'On. The.Way'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
