# Generated by Django 5.1 on 2024-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On . The .Way', 'On. The.Way')], default='Pending', max_length=50),
        ),
    ]
