# Generated by Django 5.1 on 2024-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_orderplaced_deleted_alter_orderplaced_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('esewa', 'esewa')], default='esewa', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On . The .Way', 'On. The.Way')], default='Pending', max_length=50),
        ),
    ]
