# Generated by Django 5.1 on 2024-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_orderplaced_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On . The .Way', 'On. The.Way'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
