# Generated by Django 5.1 on 2024-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_orderplaced_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('On . The .Way', 'On. The.Way')], default='Pending', max_length=50),
        ),
    ]
