# Generated by Django 5.1 on 2024-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_orderplaced_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On . The .Way', 'On. The.Way')], default='Pending', max_length=50),
        ),
    ]
