# Generated by Django 5.1 on 2024-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On . The .Way', 'On. The.Way'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
