# Generated by Django 5.1 on 2024-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('On . The .Way', 'On. The.Way')], default='Pending', max_length=50),
        ),
    ]
