# Generated by Django 5.1 on 2024-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On . The .Way', 'On. The.Way'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
