# Generated by Django 5.1 on 2024-09-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On . The .Way', 'On. The.Way'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
